// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: chats/chat_member.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRole int32

const (
	ChatRole_MEMBER ChatRole = 1
	ChatRole_ADMIN  ChatRole = 2
)

// Enum value maps for ChatRole.
var (
	ChatRole_name = map[int32]string{
		1: "MEMBER",
		2: "ADMIN",
	}
	ChatRole_value = map[string]int32{
		"MEMBER": 1,
		"ADMIN":  2,
	}
)

func (x ChatRole) Enum() *ChatRole {
	p := new(ChatRole)
	*p = x
	return p
}

func (x ChatRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chats_chat_member_proto_enumTypes[0].Descriptor()
}

func (ChatRole) Type() protoreflect.EnumType {
	return &file_chats_chat_member_proto_enumTypes[0]
}

func (x ChatRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ChatRole) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ChatRole(num)
	return nil
}

// Deprecated: Use ChatRole.Descriptor instead.
func (ChatRole) EnumDescriptor() ([]byte, []int) {
	return file_chats_chat_member_proto_rawDescGZIP(), []int{0}
}

type ChatMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId *string   `protobuf:"bytes,1,opt,name=chatId" json:"chatId,omitempty"`
	UserId *string   `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	Role   *ChatRole `protobuf:"varint,3,opt,name=role,enum=chatpb.ChatRole" json:"role,omitempty"`
}

func (x *ChatMember) Reset() {
	*x = ChatMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chats_chat_member_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMember) ProtoMessage() {}

func (x *ChatMember) ProtoReflect() protoreflect.Message {
	mi := &file_chats_chat_member_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMember.ProtoReflect.Descriptor instead.
func (*ChatMember) Descriptor() ([]byte, []int) {
	return file_chats_chat_member_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMember) GetChatId() string {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return ""
}

func (x *ChatMember) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ChatMember) GetRole() ChatRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ChatRole_MEMBER
}

var File_chats_chat_member_proto protoreflect.FileDescriptor

var file_chats_chat_member_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x61, 0x74, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x68, 0x61, 0x74, 0x70,
	0x62, 0x22, 0x62, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x2a, 0x21, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6c,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x02, 0x42, 0x1e, 0x5a, 0x1c, 0x6d, 0x65, 0x73, 0x73,
	0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x74,
	0x73, 0x3b, 0x63, 0x68, 0x61, 0x74, 0x70, 0x62,
}

var (
	file_chats_chat_member_proto_rawDescOnce sync.Once
	file_chats_chat_member_proto_rawDescData = file_chats_chat_member_proto_rawDesc
)

func file_chats_chat_member_proto_rawDescGZIP() []byte {
	file_chats_chat_member_proto_rawDescOnce.Do(func() {
		file_chats_chat_member_proto_rawDescData = protoimpl.X.CompressGZIP(file_chats_chat_member_proto_rawDescData)
	})
	return file_chats_chat_member_proto_rawDescData
}

var file_chats_chat_member_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chats_chat_member_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chats_chat_member_proto_goTypes = []interface{}{
	(ChatRole)(0),      // 0: chatpb.ChatRole
	(*ChatMember)(nil), // 1: chatpb.ChatMember
}
var file_chats_chat_member_proto_depIdxs = []int32{
	0, // 0: chatpb.ChatMember.role:type_name -> chatpb.ChatRole
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chats_chat_member_proto_init() }
func file_chats_chat_member_proto_init() {
	if File_chats_chat_member_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chats_chat_member_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chats_chat_member_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chats_chat_member_proto_goTypes,
		DependencyIndexes: file_chats_chat_member_proto_depIdxs,
		EnumInfos:         file_chats_chat_member_proto_enumTypes,
		MessageInfos:      file_chats_chat_member_proto_msgTypes,
	}.Build()
	File_chats_chat_member_proto = out.File
	file_chats_chat_member_proto_rawDesc = nil
	file_chats_chat_member_proto_goTypes = nil
	file_chats_chat_member_proto_depIdxs = nil
}
